# Generated by Django 6.0.5 on 2026-06-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('verification_question', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_answer_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('overall_grade', models.CharField(max_length=10)),
                ('overall_summary', models.TextField(blank=True, null=True)),
                ('candidate_summary', models.TextField(blank=True, null=True)),
                ('competency_analysis', models.JSONField(blank=True, null=True)),
                ('fit_analysis', models.JSONField(blank=True, null=True)),
                ('strengths', models.JSONField(blank=True, null=True)),
                ('concerns', models.JSONField(blank=True, null=True)),
                ('check_points', models.JSONField(blank=True, null=True)),
                ('final_comment', models.TextField(blank=True, null=True)),
                ('judge_status', models.CharField(blank=True, default='not_checked', max_length=30, null=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analysis_reports',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('team_composition', models.TextField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='company_infos', to='api.account')),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('evaluation_point', models.TextField(blank=True, null=True)),
                ('related_evidence', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=30, null=True)),
                ('priority', models.CharField(blank=True, max_length=30, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('interviewer_memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_report', models.ForeignKey(db_column='analysis_report_id', on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='api.analysisreport')),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=30, null=True)),
                ('major', models.CharField(blank=True, max_length=30, null=True)),
                ('career_level', models.CharField(max_length=50)),
                ('required_skills', models.JSONField()),
                ('preferred_skills', models.JSONField(blank=True, null=True)),
                ('main_tasks', models.TextField(blank=True, null=True)),
                ('hiring_reason', models.TextField(blank=True, null=True)),
                ('work_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_info', models.ForeignKey(blank=True, db_column='company_info_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='api.companyinfo')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='api.account')),
            ],
            options={
                'db_table': 'job_posts',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_post', models.ForeignKey(db_column='job_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='api.jobpost')),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='job_post',
            field=models.ForeignKey(db_column='job_post_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='api.jobpost'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(max_length=50)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('masked_text', models.TextField(blank=True, null=True)),
                ('parse_status', models.CharField(default='pending', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='api.applicant')),
            ],
            options={
                'db_table': 'resumes',
            },
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='resume',
            field=models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='api.resume'),
        ),
    ]
