# Generated by Django 6.0.5 on 2026-07-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysisreport_version_user_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='status',
            field=models.CharField(choices=[('onqueue', 'On queue'), ('processing', 'Processing'), ('done', 'Done'), ('fail', 'Fail')], default='onqueue', max_length=30),
        ),
    ]
