# Generated by Django 6.0.5 on 2026-06-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_account_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='employ_style',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='team_composition',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
