# Generated by Django 6.0.5 on 2026-06-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_companyinfo_company_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
